Repository knative-extensions/func-tastic, pull requests merged in 2022-09, with the labels that each got.

#6 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, skip-review

#8 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#9 Fix gofmt and goimports errors in CI
  go/improve/handle.go
  go/improve/handle_test.go
  go/uppercase/handle.go
Labels: approved, size/XS, lgtm

#3 Add a sample of Python function
  python/numpy/.gitignore
  python/numpy/Procfile
  python/numpy/README.md
  python/numpy/func.py
  python/numpy/func.yaml
  python/numpy/func_test.py
  python/numpy/requirements.txt
  python/numpy/runtime.txt
Labels: approved, size/L, lgtm

#11 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#12 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
